### ISSUE TITLE
[FEATURE REQUEST] Remove mask pin

### ISSUE THREAD

**Issue by Ares9323** [AKaKLya/MatHelper#2]
Hi! I've just downloaded your plugin and I was trying its features, the add-pin thing is so cool but my favorite is the category assigner!

Maybe I'm missing something, I was wondering if it's already possible to reset the pins of a node in any way instead of having to recreate it from scratch.

Maybe a toggle button would be enough (instead of the "Add mask pin"), if the node doesn't have the selected pin exposed it shows it when clicked, otherwise it hides it.

Thank you for this tool, I really love it!

**Comment by AKaKLya** [comment]
thanks ,  
I updated the [Add or Remove Pin] in version 5.3, 
You can download the New Release version [MatHelperV2.1-5.3]
but the button still named [Add Mask Pin] ,( I have no better name T_T)

known bug : 
I have a node . the node has these pin : [R,G,B,A] ,  when i remove [R] , it will be [G,B,A].  that's ok. 
but , when i add [R] pin again , it will be [G,B,A,R].  there are no sort . 


One day ,I want to restart Engine in c++ code , but i don't know how to do it .
so i downloaded your plugin which named [Restart Unreal Editor] , and i learend something.

**Comment by AKaKLya** [comment]
updated Release version  [MatHelperV2.1-5.3] , 
you can download it now.

**Comment by Ares9323** [comment]
> but the button still named [Add Mask Pin] ,( I have no better name T_T)

I think that "TogglePin" could be a good name for the button, but for me it's more than enough if it works!

> known bug :
I have a node . the node has these pin : [R,G,B,A] , when i remove [R] , it will be [G,B,A]. that's ok.
but , when i add [R] pin again , it will be [G,B,A,R]. there are no sort .

This is funny, I haven't looked how your code works but hearing this I guess there is "no decent way" to fix this without removing all the pins and re-adding them again in order, and that's not an option IMHO since you could accidentally disconnect other connected pins.

> One day ,I want to restart Engine in c++ code , but i don't know how to do it .
so i downloaded your plugin which named [Restart Unreal Editor] , and i learend something.

I'm really happy that you appreciated my plugin, I made it because I needed it and I thought that it should be available to anyone, Unreal needs to be restarted way too frequently! It was one of my first experiments with the engine's source code, I've learned something from it too!

___

Thanks for your tool again!
